project:
  type: website

website:
  title: "niozpy"
  navbar:
    left:
      - href: index.qmd
        text: Set-up instructions

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
